xspring.application.name=BorrowBuddy

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/borrowbuddy
spring.datasource.username=root
spring.datasource.password=tojicrypto123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# The Auto-Builder
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true